#! /bin/bash

#Author: Batel Peretz
#Description: This script will ping a remote host and modify 

hosts="2.53.189.233"
ping -c1 $hosts &> /dev/null   
	if [ $? -eq 0 ]
	then
	echo $hosts OK
	else 
	echo $hosts something wrong! 
	fi		



